class PolygonIterError(Exception):
    """Base exception for all application errors."""

# Polygon-related errors
class InvalidNumSidesError(PolygonIterError): ...
class InvalidRatioError(PolygonIterError): ...
class InvalidIterationsError(PolygonIterError): ...

# Plot-related errors
class InvalidAlphaError(PolygonIterError): ...
class InvalidColorError(PolygonIterError): ...
class RenderingError(PolygonIterError): ...
class InvalidFigureSizeError(PolygonIterError): ...