"""
Core domain primitives for polygon construction and representation.
 
This module defines the foundational data types used throughout the package:
Point, Polygon, and PolygonSequence. These are pure data containers with
minimal behaviour — geometric algorithms live in transforms.py.
"""

from dataclasses import dataclass
import math


@dataclass
class Point:
    """A point in 2D Euclidean space.
 
    Attributes:
        x: Horizontal coordinate.
        y: Vertical coordinate.
    """

    x: float
    y: float

    def as_tuple(self) -> tuple[float, float]:
        """Return the point as a plain (x, y) tuple.
 
        Useful for interoperability with libraries that expect raw tuples,
        such as Matplotlib.
 
        Returns:
            A tuple (x, y) with the point's coordinates.
        """
        return (self.x, self.y)


@dataclass
class Polygon:
    """An ordered sequence of Points representing a polygon.
 
    Supports both open and closed polygons. When closed, the last point
    is expected to coincide with the first, explicitly completing the shape.
 
    Attributes:
        points: Ordered list of vertices. For closed polygons, the first
            point is repeated as the last.
        closed: Whether the polygon is closed. Defaults to True.
    """

    points: list[Point]
    closed: bool = True

    def __len__(self):
        """Return the number of points, including the closing point if present."""
        return len(self.points)
    
    def __iter__(self):
        """Iterate over the polygon's points."""
        return iter(self.points)
    
    def __getitem__(self, index: int) -> Point:
        """Return the point at the given index.
 
        Args:
            index: Position of the desired point. Supports negative indexing.
 
        Returns:
            The Point at the specified index.
        """
        return self.points[index]
    
    @classmethod
    def regular(
        cls,
        num_sides: int,
        radius: float = 1.0,
        center: Point | None = None,
        closed: bool = True
    ) -> "Polygon":
        """Construct a regular polygon inscribed in a circle.
 
        Vertices are evenly distributed around a circle of the given radius.
        The polygon is rotated for visual balance: flat-side-up for even-sided
        polygons, point-up for odd-sided ones.
 
        Args:
            num_sides: Number of sides (and vertices) of the polygon.
                Must be greater than or equal to 3.
            radius: Radius of the circumscribed circle. Defaults to 1.0.
            center: Centre point of the polygon. Defaults to the origin (0, 0).
            closed: Whether to close the polygon by repeating the first vertex
                at the end. Defaults to True.
 
        Returns:
            A Polygon instance with evenly spaced vertices.
 
        Example:
            >>> triangle = Polygon.regular(3)
            >>> hexagon = Polygon.regular(6, radius=2.0, center=Point(1.0, 1.0))
        """
        center = center or Point(0.0, 0.0)

        # Include the first point to close the polygon
        num_points = num_sides + 1 if closed else num_sides
        central_angle = 2 * math.pi / num_sides

        # Rotate the polygon for a more visually appealing orientation
        if num_sides % 2 == 0:
            init_angle = central_angle / 2
        else:
            init_angle = central_angle / 2 - math.pi / 2
        
        points = []
        for i in range(num_points):
            angle = init_angle + central_angle * i
            x = radius * math.cos(angle) + center.x
            y = radius * math.sin(angle) + center.y
            points.append(Point(x, y))

        return cls(points, closed)

    
    def x_coords(self) -> list[float]:
        """Return the x-coordinates of all points.
 
        Returns:
            A list of x values in vertex order.
        """
        return [p.x for p in self.points]
    
    def y_coords(self) -> list[float]:
        """Return the y-coordinates of all points.
 
        Returns:
            A list of y values in vertex order.
        """
        return [p.y for p in self.points]


@dataclass
class PolygonSequence:
    """An ordered collection of Polygons produced by iterative transformation.
 
    Stores the full history of polygons generated by repeatedly applying
    a linear interpolation transform, along with the parameters used to
    produce it.
 
    Attributes:
        polygons: Ordered list of Polygon instances, from the original
            to the final transformed state.
        t: Interpolation ratio used at each transformation step.
        iterations: Number of transformations applied to produce the sequence.
    """

    polygons: list[Polygon]
    t: float
    iterations: int

    def __len__(self):
        """Return the number of polygons in the sequence."""
        return len(self.polygons)

    def __iter__(self):
        """Iterate over the polygons in transformation order."""
        return iter(self.polygons)